#!/bin/sh
objcopy -O binary -R .note -R .comment -R .ARM.attributes -S -j .text linux-system.axf .text
objcopy -O binary -R .note -R .comment -R .ARM.attributes -S -j .monitor linux-system.axf .monitor
