#!/bin/sh
${CROSS_COMPILE}objcopy -O binary -R .note -R .comment -R .ARM.attributes -S -j .text linux-system.axf .text
${CROSS_COMPILE}objcopy -O binary -R .note -R .comment -R .ARM.attributes -S -j .monitor linux-system.axf .monitor
